services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA='/var/lib/postgresql/data/pgdata'
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '6000:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - DB_CONNECTION_STRING=postgresql://postgres:password@db:5432/postgres
    ports:
      - '3000:3000'
    depends_on:
      - db